# Generated by Django 5.0.5 on 2024-05-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theater',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
